### ISSUE TITLE
How is the aspect-opinion pairs generated from raw reviews?

### ISSUE THREAD

**Issue by peter-peng-w** [PreferredAI/seer#1]
Hi, as the aspect-opinion pairs extracted for each sentences are quite important for this model, is it possible to share the script or pipeline of how to extract aspect and opinion from the raw review text? Thanks.

**Comment by lthoang** [comment]
Hi, I used [Sentires](https://github.com/evison/Sentires) for extracting aspect-opinion-sentiment from review sentences. You can also take a look a quick guide how to use at this repository https://github.com/lileipisces/Sentires-Guide

**Comment by peter-peng-w** [comment]
> Hi, I used [Sentires](https://github.com/evison/Sentires) for extracting aspect-opinion-sentiment from review sentences. You can also take a look a quick guide how to use at the took at this repository https://github.com/lileipisces/Sentires-Guide

I see, thanks for your clarification!
